apiVersion: v1
kind: ServiceAccount
metadata:
  name: emrgpay-backend
  namespace: emrgpay
  annotations:
    azure.workload.identity/client-id: "509bc1a4-40a5-4096-80ad-1204ef8f841e"
  labels:
    azure.workload.identity/use: "true"
